### ISSUE TITLE
Settings Menu - Error

### ISSUE THREAD

**Issue by NebulaXL** [AlizerUncaged/CGHM-External-UI#1]
When I open the settings tab from the settings Icon, the Application crashes with the error: System.Collections.Generic.KeyNotFoundException: 'The given key was not present in the dictionary.'
Line: 87 File: Settings.xaml.cs

**Comment by AlizerUncaged** [comment]
![image](https://user-images.githubusercontent.com/86959368/142454517-b2a620cc-92f1-4ccb-9ed5-b0485451f832.png)

**Comment by AlizerUncaged** [comment]
wait my mom told me to sleep its 4am ill fix the bug tomorrow  maybe just add check if key exists in dictionary oh no my mom is downstairs i hear her footsteps heading to my room i need to sleep now bye ill check it tomorrow
