### ISSUE TITLE
dont working

### ISSUE THREAD

**Issue by DEEXZON** [AlizerUncaged/CGHM-External-UI#3]
![image](https://user-images.githubusercontent.com/94984678/143280697-7cb56ed7-5cf4-498a-944b-320b3395f014.png)
![image](https://user-images.githubusercontent.com/94984678/143280740-ff8ca298-5f7a-4879-b0ed-47695305a927.png)

**Comment by KingosWolfos** [comment]
what i need to do with it

**Comment by NebulaXL** [comment]
when does this error occur?

**Comment by DEEXZON** [comment]
At startup .exe file четверг, 25 ноября 2021г., 02:36 +07:00 от Poseidon Phoenix  ***@***.*** :
