### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by KingosWolfos** [AlizerUncaged/CGHM-External-UI#7]
![bug2](https://user-images.githubusercontent.com/70902737/143284415-78ee0744-37ce-4455-9a70-34e35b72304d.PNG)
![bug](https://user-images.githubusercontent.com/70902737/143284417-fb46e591-bd3b-4006-8095-a95ad20d8f8f.PNG)

**Comment by NebulaXL** [comment]
when does this error occur?
